package io.maxluxs.flagship.sample

import androidx.compose.runtime.Composable
import androidx.compose.ui.unit.dp
import io.maxluxs.flagship.core.Flagship
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.launch

/**
 * Example of using typed flags generated by flagship-codegen.
 * 
 * This demonstrates how to use the generated Flags object for type-safe flag access.
 * 
 * Note: The generated Flags object is available after running ./gradlew generateFlags
 * and will be in package io.maxluxs.flagship.generated
 */
@Composable
fun TypedFlagsExample(scope: CoroutineScope) {
    // Example usage of generated typed flags:
    // 
    // lifecycleScope.launch {
    //     // Boolean flag
    //     if (io.maxluxs.flagship.generated.Flags.NewUi.enabled()) {
    //         showNewUI()
    //     }
    //     
    //     // Typed values
    //     val timeout: Int = io.maxluxs.flagship.generated.Flags.ApiTimeout.value()
    //     val message: String = io.maxluxs.flagship.generated.Flags.WelcomeMessage.value()
    //     
    //     // Experiments
    //     val variant = io.maxluxs.flagship.generated.Flags.CheckoutFlow.variant()
    //     when (variant) {
    //         "control" -> showLegacyCheckout()
    //         "A" -> showNewCheckout()
    //         "B" -> showAlternativeCheckout()
    //     }
    // }
    
    // For now, use Flagship API directly until codegen is integrated
    scope.launch {
        // Boolean flag
        val newUiEnabled = Flagship.isEnabled("new_ui", default = false)
        
        // Typed values (using value() extension function)
        val timeout: Int = Flagship.value("api_timeout", default = 5000)
        val message: String = Flagship.value("welcome_message", default = "Welcome!")
        
        // Or using get() method (both work)
        // val timeout: Int = Flagship.get("api_timeout", default = 5000)
        
        // Use the values...
    }
}

/**
 * Integration guide for typed flags:
 * 
 * 1. Create flags.json in project root (see flags.json.example)
 * 2. Add plugin to build.gradle.kts:
 *    ```kotlin
 *    plugins {
 *        id("io.maxluxs.flagship.codegen")
 *    }
 *    ```
 * 3. Configure codegen:
 *    ```kotlin
 *    flagshipCodegen {
 *        configFile = file("flags.json")
 *        outputDir = file("build/generated/flagship")
 *        packageName = "com.example.app.flags"
 *    }
 *    ```
 * 4. Run: ./gradlew generateFlags
 * 5. Use generated Flags object:
 *    ```kotlin
 *    import com.example.app.flags.Flags
 *    
 *    lifecycleScope.launch {
 *        if (Flags.NewUi.enabled()) {
 *            // ...
 *        }
 *    }
 *    ```
 */

